### PR TITLE
Fix Table Regression Bugs

### LINKED ISSUE #629: Table refactor regressions and other minor issues
#### Table regressions
Most issues had to do with searching, checkout previous versions of teleport for comparison

audit log:
- [ ] cannot search by date as seen in column

session recording:
- [ ] cannot search by duration

active sessions:
- [ ] looks like we added a search bar, but it barely works

node list:
- [ ] searching by keyword "tunnel", when there are tunnels, does not work

recovery table:
- [ ] table `device successfully enrolled`, when hovering, the row without the `remove` btn does not highlight entire row

#### Others
Just some other minor stuff i noticed

trusted clusters
- [ ] no tooltip when add button is disabled like others
 
support links:
- [ ] the troubleshooting links does not go to the proper page anymore, need to be updated

### PR DESCRIPTION
**Pull request by rudream**
## Purpose

This PR resolves #629 

Fixes some table regressions and other improvements

## Implementation

- Added `searchableProps` to Table config to allow searching through the pieces of data that are part of the object but that aren't indexed by the table columns. 

- Added search functionality to arrays of objects and arrays of strings, this is useful in the case of searching through Active Sessions because you are now able to search by participants. 

- Added search functionality for booleans, eg. you can now search `tunnel` and get rows that have `tunnel: true`. 

### Searching through Active Sessions by duration and by users
searchingsessions2

### CODE REVIEW

File: packages/design/src/DataTable/useTable.ts [hunk 1]
```diff
@@ -172,14 +173,39 @@ function searchAndFilterCb<T>(
...
+  }
+  if (typeof targetValue === 'boolean') {
+    return (
+      propName.toLocaleLowerCase().includes(searchValue.toLocaleLowerCase()) &&
+      targetValue
+    );
+  }
+
+  // For searching through elements of an array
+  if (Array.isArray(targetValue)) {
```
Comment (kimlisa) [inline packages/design/src/DataTable/useTable.ts:190]: this assumes the items are of type `string`, what happens if its other than string?

File: packages/design/src/DataTable/useTable.ts [hunk 2]
```diff
@@ -172,14 +173,39 @@ function searchAndFilterCb<T>(
...
 ) {
-  if (propName === 'tags') {
-    return targetValue.some(item => {
-      return item.toLocaleLowerCase().includes(searchValue.toLocaleLowerCase());
-    });
-  }
   if (propName.toLocaleLowerCase().includes('date')) {
     return displayDate(targetValue).includes(searchValue);
   }
+  if (propName.toLocaleLowerCase().includes('time')) {
```
Comment (kimlisa) [inline packages/design/src/DataTable/useTable.ts:179]: `propName.toLocaleLowerCase()` is getting called multiple times needlessly

File: packages/design/src/DataTable/useTable.ts [hunk 3]
```diff
@@ -172,14 +173,39 @@ function searchAndFilterCb<T>(
...
+    return displayDateTime(targetValue).includes(searchValue);
+  }
+  if (typeof targetValue === 'boolean') {
+    return (
+      propName.toLocaleLowerCase().includes(searchValue.toLocaleLowerCase()) &&
+      targetValue
+    );
+  }
```
Comment (kimlisa) [inline packages/design/src/DataTable/useTable.ts:187]: i'm not sure how i feel about this and others b/c we are depending on the propName to include a certain keyword, why did we go away from sending in custom functions?

File: packages/design/src/DataTable/useTable.ts [hunk 4]
```diff
@@ -172,14 +173,39 @@ function searchAndFilterCb<T>(
...
+
+  // For searching through elements of an array
+  if (Array.isArray(targetValue)) {
+    return targetValue.some(item => {
+      if (typeof item === 'object') {
```
Comment (hatched) [inline packages/design/src/DataTable/useTable.ts:192]: You'll want to be more robust on this check as...

```
>  typeof null === "object"
<- true
```

File: packages/design/src/DataTable/useTable.ts [hunk 5]
```diff
@@ -172,14 +173,39 @@ function searchAndFilterCb<T>(
...
+          if (
+            item[key]
+              .toLocaleLowerCase()
+              .includes(searchValue.toLocaleLowerCase())
+          ) {
+            return true;
+          }
+        }
+      } else {
+        return item
```
Comment (hatched) [inline packages/design/src/DataTable/useTable.ts:203]: This assumes it's a `string`, it appears that it could be possible that it's not as you're only validating the type of the value if it's _not_ an `array`. You might want to combine these checks so that you're not handling array values differently. You could do this by simply placing the `targetValue` into an array if it isn't one and then looping over each value with the same validation checks.

**Review by hatched — CHANGES_REQUESTED** [review]

File: packages/design/src/DataTable/useTable.ts (hunk 3 above)
Comment (rudream) [reply packages/design/src/DataTable/useTable.ts:187]: The custom search functions led to too much repeated code

**Comment by rudream** [comment]
### Changes

Updated `Troubleshooting` link to docs

image

File: packages/design/src/DataTable/useTable.ts [hunk 6]
```diff
@@ -39,13 +40,32 @@ export default function useTable<T>({
...
+        if (isMatched) {
+          return true;
+        }
+      }
+
+      // No match found.
+      return false;
+    };
+  });
+
```
Comment (kimlisa) [inline packages/design/src/DataTable/useTable.ts:60]: lol i know i wrote this, but it's unnecessary pre-optimization (define the function once) lets define it regularly

```
function searchAndFilterCb(targetValue: any, searchValue: string, propName: keyof T & string) {
     for (const matcher of customSearchMatchers) {
        const isMatched = matcher(targetValue, searchValue, propName);
        if (isMatched) {
          return true;
        }
      }

      // No match found.
      return false;
}
```

File: packages/teleport/src/components/NodeList/NodeList.tsx [hunk 7]
```diff
@@ -96,6 +105,23 @@ export const renderAddressCell = ({ addr, tunnel }: Node) => (
...
+  if (
+    propName === 'tunnel' &&
+    targetValue &&
+    propName.includes(searchValue.toLocaleLowerCase())
+  ) {
+    console.log('reached here');
+    return true;
+  }
+
+  return false;
```
Comment (kimlisa) [inline packages/teleport/src/components/NodeList/NodeList.tsx:122]:
```suggestion
  return propName === 'tunnel' && targetValue && propName.includes(searchValue.toLocaleLowerCase())
```

File: packages/design/src/utils/match/matchers.ts [hunk 8]
```diff
@@ -0,0 +1,20 @@
+import { displayDate, displayDateTime } from 'shared/services/loc';
+import { MatchCallback } from './match';
+
+export const dateMatcher =
+  <T>(datePropNames: (keyof T & string)[]): MatchCallback<T> =>
+  (targetValue, searchValue, propName) => {
+    if (datePropNames.includes(propName)) {
+      return displayDate(targetValue).toLocaleLowerCase().includes(searchValue);
+    }
+  };
```
Comment (kimlisa) [inline packages/design/src/utils/match/matchers.ts:10]: my brain cramped reading this lol, i would save shortcut return statements for when its short and easy to read. I also tend to favor using keyword `function` whenever i can b/c it clearly states it's a function and when it concerns typing, it's easier to reason:

```suggestion
export function dateMatcher<T>(
  datePropNames: (keyof T & string)[]
): MatchCallback<T> {
  return (targetValue, searchValue, propName) => {
    if (datePropNames.includes(propName)) {
      return displayDate(targetValue).toLocaleLowerCase().includes(searchValue);
    }
  };
}
```

File: packages/teleport/src/Sessions/SessionList/SessionList.tsx [hunk 9]
```diff
@@ -98,3 +111,21 @@ type Props = {
...
 };
+
+function participantMatcher(
+  targetValue: any,
+  searchValue: string,
+  propName: keyof Session & string
+) {
+  if (propName === 'parties') {
+    return targetValue.some((participant: Participant) => {
+      if (participant.remoteAddr.toLocaleUpperCase().includes(searchValue)) {
```
Comment (kimlisa) [inline packages/teleport/src/Sessions/SessionList/SessionList.tsx:122]: on second thought, idk if we should be relying on the root searchValue transofrmation b/c someone can change it and then everything will break right? Lets also transform the search value in our matchers, and then in the root match only transform when about to match?

File: packages/teleport/src/Sessions/SessionList/SessionList.tsx [hunk 10]
```diff
@@ -98,3 +111,21 @@ type Props = {
...
+        return true;
+      }
+
+      return participant.user.toLocaleUpperCase().includes(searchValue);
+    });
+  }
+  // No match.
+  return false;
```
Comment (kimlisa) [inline packages/teleport/src/Sessions/SessionList/SessionList.tsx:130]: do we really need this? i think it returns undefined if no return statement and that's a falsey right?

**Review by kimlisa — CHANGES_REQUESTED** [review]

File: packages/teleport/src/Sessions/SessionList/SessionList.tsx (hunk 10 above)
Comment (rudream) [reply packages/teleport/src/Sessions/SessionList/SessionList.tsx:130]: correct, and the `.some` would actually return `false`

File: packages/design/src/DataTable/types.ts [hunk 11]
```diff
@@ -1,9 +1,13 @@
+import { MatchCallback } from 'design/utils/match';
+
 export type TableProps<T> = {
   data: T[];
   columns: TableColumn<T>[];
   emptyText: string;
   pagination?: PaginationConfig;
   isSearchable?: boolean;
+  searchableProps?: Extract<keyof T, string>[];
+  customSearchMatchers?: MatchCallback<T>[];
```
Comment (kimlisa) [inline packages/design/src/DataTable/types.ts:10]: lets add back the comment explaining that searchValue comes transformed to lower case

File: packages/design/src/utils/match/index.ts [hunk 12]
```diff
@@ -0,0 +1,6 @@
+import isMatch, { MatchCallback } from './match';
+import { dateMatcher, dateTimeMatcher } from './matchers';
+
+export default isMatch;
+export { dateMatcher, dateTimeMatcher };
+export type { MatchCallback };
```
Comment (kimlisa) [inline packages/design/src/utils/match/index.ts:6]: what is `export type { MatchCallback };`?

```suggestion
export { dateMatcher, dateTimeMatcher, MatchCallback };
```

File: packages/teleport/src/components/NodeList/NodeList.tsx [hunk 13]
```diff
@@ -96,6 +105,14 @@ export const renderAddressCell = ({ addr, tunnel }: Node) => (
   <Cell>{tunnel ? renderTunnel() : addr}</Cell>
 );
 
+function tunnelMatcher(
+  targetValue: any,
+  searchValue: string,
+  propName: keyof Node & string
+) {
+  return propName === 'tunnel' && targetValue && propName.includes(searchValue);
```
Comment (kimlisa) [inline packages/teleport/src/components/NodeList/NodeList.tsx:113]: makes more sense to me even though they do same thing

```suggestion
  return propName === 'tunnel' && targetValue && searchValue.includes(propName);
```

**Review by kimlisa — APPROVED** [review]
after addressing minor comments

File: packages/design/src/utils/match/index.ts (hunk 12 above)
Comment (rudream) [reply packages/design/src/utils/match/index.ts:6]: Re-exporting the type this way causes this error:

```
export 'MatchCallback' (reexported as 'MatchCallback') was not found in './match' (possible exports: default)
design/src/utils/match/index.ts
```

We can use [type-only exports](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#-type-only-imports-and-export) to fix this

File: packages/teleport/src/components/NodeList/NodeList.tsx (hunk 13 above)
Comment (kimlisa) [reply packages/teleport/src/components/NodeList/NodeList.tsx:113]: nvm, i am wrong

File: packages/design/src/utils/match/index.ts (hunk 12 above)
Comment (kimlisa) [reply packages/design/src/utils/match/index.ts:6]: ah got it thanks

**Review by hatched — APPROVED** [review]
Thanks for the updates! 👍
